[package]
name = "qiming_rust"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
crossbeam-channel = "0.5"
rayon = "1.10.0"
zhconv = "0.3.3"
rustc-hash = "2.1.1"
indexmap = "2.8.0"
